version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_prisma
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: prisma_app
      TZ: Asia/Seoul
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nestjs-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api 
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mysql
    env_file:
      - .env
    environment: 
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DB: prisma_app
    networks:
      - nestjs-network
      
networks:
  nestjs-network: